In [21]:
# Preparing pathing
%load_ext autoreload
%autoreload 2
from titanic_ml import paths
import matplotlib.pyplot as plt
import pandas as pd
from titanic_ml.common.data.eda import summarize_categorical_column, summarize_numerical_column
from titanic_ml.common.data.eda import run_eda 


from ast import For
from cmath import exp

from titanic_ml.common.experiments.runner import run_experiments, run_experiment_group_workflow
from titanic_ml.common.experiments.config import ALL_EXPERIMENTS
from titanic_ml.common.experiments.report import experiment_report, experiment_group_summary_report, baseline_summary_to_markdown, workflow_report
from titanic_ml.common.experiments.save_load import save_results, load_results, save_configs, load_configs, save_feature_effects, load_feature_effects
from titanic_ml.common.experiments.compare import leaderboard, compare_experiment_groups, summarize_group_comparison, titanic_notes_leaderboard, model_progression, analyze_feature_effect
from titanic_ml.common.models.registry import MODEL_REGISTRY
from titanic_ml.feature_engineering import add_family_features, add_has_cabin, add_title, add_full_title_feature

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
TARGET = "Survived"
ALL_EXPERIMENTS = ALL_EXPERIMENTS
for experiment_name, exp_config in ALL_EXPERIMENTS.items():
    print(f"Experiment: {experiment_name}")

train_df = pd.read_csv(paths.TRAIN_PATH)

exp_configs = ALL_EXPERIMENTS["cb03__age_imputed_title_Pclass_and_bins"]

# # Line to rerun all experiments to update the results with the latest code changes. This will take a while.
# # Uncomment to run all experiments and update results.

# for Name, exp_config in ALL_EXPERIMENTS.items():
#     print(f"Running {Name} experiments...")
#     exp_result = run_experiments(train_df, exp_config, target=TARGET, verbose=True, debug=True)
#     result_df = save_results(exp_result)
#     save_configs(exp_config)
#     if Name != 'baseline__raw':
#         comparison = compare_experiment_groups(
#             results_df=result_df,
#             reference_group="baseline__raw",
#             compare_groups=[Name],
#         )
#         feature_effect = analyze_feature_effect(comparison)
#         save_feature_effects(feature_effect)

Experiment: baseline__raw
Experiment: fe01__family
Experiment: fe02__has_cabin
Experiment: fe03__deck
Experiment: fe04__cabin_features
Experiment: fe05__title
Experiment: fe06__age_imputation_title
Experiment: fe07__age_imputation_title_pclass
Experiment: fe08__fare_per_family_member
Experiment: fe09__ticket_group_size
Experiment: fe10__fare_per_ticket_member
Experiment: fe11__age_bin
Experiment: fe12__sex_pclass
Experiment: cb01__age_and_bins
Experiment: cb02__age_imputed_title_and_bins
Experiment: cb03__age_imputed_title_Pclass_and_bins
Running baseline__raw experiments...
running exp: {'name': 'baseline__raw__logreg', 'features': ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], 'feature_engineering': [], 'preprocessing': {'numeric_features': ['Age', 'SibSp', 'Parch', 'Fare'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'logreg', 'model_params': {'max_iter': 1000, 'random_state': 42}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Base logistic regression, using raw configuration. Baseline for comparison.', 'stage': 'baseline', 'feature_group': 'raw', 'group': 'baseline__raw'}
Running experiment: baseline__raw__logreg

Experiment 'baseline__raw__logreg' results:
  stage: baseline
  feature_group: raw
  model_name: logreg
  group: baseline__raw
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.786
  test_accuracy_std: 0.018
  train_accuracy_mean: 0.803
  train_accuracy_std: 0.005
  test_precision_mean: 0.736
  test_precision_std: 0.036
  train_precision_mean: 0.762
  train_precision_std: 0.011
  test_recall_mean: 0.693
  test_recall_std: 0.038
  train_recall_mean: 0.708
  train_recall_std: 0.015
  test_f1_mean: 0.713
  test_f1_std: 0.026
  train_f1_mean: 0.734
  train_f1_std: 0.008
  fit_time_mean: 0.02
  score_time_mean: 0.014
  domain:
  notes: Base logistic regression, using raw configuration. Baseline for comparison.

Experiment 'baseline__raw__logreg' completed.
----------------------------------------
running exp: {'name': 'baseline__raw__knn', 'features': ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], 'feature_engineering': [], 'preprocessing': {'numeric_features': ['Age', 'SibSp', 'Parch', 'Fare'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'knn', 'model_params': {'n_neighbors': 5}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Base kneighbors classifier, using raw configuration. Baseline for comparison.', 'stage': 'baseline', 'feature_group': 'raw', 'group': 'baseline__raw'}
Running experiment: baseline__raw__knn

Experiment 'baseline__raw__knn' results:
  stage: baseline
  feature_group: raw
  model_name: knn
  group: baseline__raw
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.809
  test_accuracy_std: 0.021
  train_accuracy_mean: 0.861
  train_accuracy_std: 0.01
  test_precision_mean: 0.775
  test_precision_std: 0.044
  train_precision_mean: 0.843
  train_precision_std: 0.013
  test_recall_mean: 0.713
  test_recall_std: 0.038
  train_recall_mean: 0.783
  train_recall_std: 0.019
  test_f1_mean: 0.742
  test_f1_std: 0.026
  train_f1_mean: 0.812
  train_f1_std: 0.015
  fit_time_mean: 0.015
  score_time_mean: 0.02
  domain:
  notes: Base kneighbors classifier, using raw configuration. Baseline for comparison.

Experiment 'baseline__raw__knn' completed.
----------------------------------------
running exp: {'name': 'baseline__raw__svc', 'features': ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], 'feature_engineering': [], 'preprocessing': {'numeric_features': ['Age', 'SibSp', 'Parch', 'Fare'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'svc', 'model_params': {'C': 1.0, 'kernel': 'rbf', 'gamma': 'scale', 'probability': False, 'random_state': 42}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Base SVC, using raw configuration. Baseline for comparison.', 'stage': 'baseline', 'feature_group': 'raw', 'group': 'baseline__raw'}
Running experiment: baseline__raw__svc

Experiment 'baseline__raw__svc' results:
  stage: baseline
  feature_group: raw
  model_name: svc
  group: baseline__raw
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.827
  test_accuracy_std: 0.015
  train_accuracy_mean: 0.834
  train_accuracy_std: 0.006
  test_precision_mean: 0.813
  test_precision_std: 0.029
  train_precision_mean: 0.819
  train_precision_std: 0.01
  test_recall_mean: 0.716
  test_recall_std: 0.045
  train_recall_mean: 0.729
  train_recall_std: 0.015
  test_f1_mean: 0.76
  test_f1_std: 0.026
  train_f1_mean: 0.771
  train_f1_std: 0.009
  fit_time_mean: 0.023
  score_time_mean: 0.018
  domain:
  notes: Base SVC, using raw configuration. Baseline for comparison.

Experiment 'baseline__raw__svc' completed.
----------------------------------------
running exp: {'name': 'baseline__raw__decision_tree', 'features': ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], 'feature_engineering': [], 'preprocessing': {'numeric_features': ['Age', 'SibSp', 'Parch', 'Fare'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'decision_tree', 'model_params': {'max_depth': 4, 'min_samples_leaf': 5, 'random_state': 42}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Base decision tree, using raw configuration. Baseline for comparison.', 'stage': 'baseline', 'feature_group': 'raw', 'group': 'baseline__raw'}
Running experiment: baseline__raw__decision_tree

Experiment 'baseline__raw__decision_tree' results:
  stage: baseline
  feature_group: raw
  model_name: decision_tree
  group: baseline__raw
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.803
  test_accuracy_std: 0.023
  train_accuracy_mean: 0.832
  train_accuracy_std: 0.005
  test_precision_mean: 0.828
  test_precision_std: 0.03
  train_precision_mean: 0.877
  train_precision_std: 0.046
  test_recall_mean: 0.617
  test_recall_std: 0.093
  train_recall_mean: 0.659
  train_recall_std: 0.05
  test_f1_mean: 0.702
  test_f1_std: 0.055
  train_f1_mean: 0.749
  train_f1_std: 0.017
  fit_time_mean: 0.016
  score_time_mean: 0.015
  domain:
  notes: Base decision tree, using raw configuration. Baseline for comparison.

Experiment 'baseline__raw__decision_tree' completed.
----------------------------------------
running exp: {'name': 'baseline__raw__random_forest', 'features': ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], 'feature_engineering': [], 'preprocessing': {'numeric_features': ['Age', 'SibSp', 'Parch', 'Fare'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'random_forest', 'model_params': {'n_estimators': 200, 'max_depth': 5, 'min_samples_leaf': 3, 'random_state': 42, 'n_jobs': -1}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Base random forest, using raw configuration. Baseline for comparison.', 'stage': 'baseline', 'feature_group': 'raw', 'group': 'baseline__raw'}
Running experiment: baseline__raw__random_forest

Experiment 'baseline__raw__random_forest' results:
  stage: baseline
  feature_group: raw
  model_name: random_forest
  group: baseline__raw
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.822
  test_accuracy_std: 0.02
  train_accuracy_mean: 0.85
  train_accuracy_std: 0.007
  test_precision_mean: 0.824
  test_precision_std: 0.02
  train_precision_mean: 0.873
  train_precision_std: 0.016
  test_recall_mean: 0.681
  test_recall_std: 0.062
  train_recall_mean: 0.714
  train_recall_std: 0.015
  test_f1_mean: 0.744
  test_f1_std: 0.041
  train_f1_mean: 0.785
  train_f1_std: 0.011
  fit_time_mean: 0.363
  score_time_mean: 0.063
  domain:
  notes: Base random forest, using raw configuration. Baseline for comparison.

Experiment 'baseline__raw__random_forest' completed.
----------------------------------------
running exp: {'name': 'baseline__raw__extra_trees', 'features': ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], 'feature_engineering': [], 'preprocessing': {'numeric_features': ['Age', 'SibSp', 'Parch', 'Fare'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'extra_trees', 'model_params': {'n_estimators': 200, 'max_depth': 5, 'min_samples_leaf': 3, 'random_state': 42, 'n_jobs': -1}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Base extra trees, using raw configuration. Baseline for comparison.', 'stage': 'baseline', 'feature_group': 'raw', 'group': 'baseline__raw'}
Running experiment: baseline__raw__extra_trees

Experiment 'baseline__raw__extra_trees' results:
  stage: baseline
  feature_group: raw
  model_name: extra_trees
  group: baseline__raw
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.804
  test_accuracy_std: 0.012
  train_accuracy_mean: 0.813
  train_accuracy_std: 0.004
  test_precision_mean: 0.791
  test_precision_std: 0.009
  train_precision_mean: 0.806
  train_precision_std: 0.012
  test_recall_mean: 0.664
  test_recall_std: 0.041
  train_recall_mean: 0.675
  train_recall_std: 0.013
  test_f1_mean: 0.721
  test_f1_std: 0.025
  train_f1_mean: 0.735
  train_f1_std: 0.006
  fit_time_mean: 0.28
  score_time_mean: 0.07
  domain:
  notes: Base extra trees, using raw configuration. Baseline for comparison.

Experiment 'baseline__raw__extra_trees' completed.
----------------------------------------
running exp: {'name': 'baseline__raw__xgb', 'features': ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], 'feature_engineering': [], 'preprocessing': {'numeric_features': ['Age', 'SibSp', 'Parch', 'Fare'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'xgb', 'model_params': {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.05, 'subsample': 0.8, 'colsample_bytree': 0.8, 'random_state': 42, 'eval_metric': 'logloss'}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Base xgb, using raw configuration. Baseline for comparison.', 'stage': 'baseline', 'feature_group': 'raw', 'group': 'baseline__raw'}
Running experiment: baseline__raw__xgb

Experiment 'baseline__raw__xgb' results:
  stage: baseline
  feature_group: raw
  model_name: xgb
  group: baseline__raw
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.826
  test_accuracy_std: 0.025
  train_accuracy_mean: 0.885
  train_accuracy_std: 0.004
  test_precision_mean: 0.811
  test_precision_std: 0.033
  train_precision_mean: 0.895
  train_precision_std: 0.01
  test_recall_mean: 0.713
  test_recall_std: 0.06
  train_recall_mean: 0.793
  train_recall_std: 0.006
  test_f1_mean: 0.758
  test_f1_std: 0.041
  train_f1_mean: 0.841
  train_f1_std: 0.005
  fit_time_mean: 0.474
  score_time_mean: 0.017
  domain:
  notes: Base xgb, using raw configuration. Baseline for comparison.

Experiment 'baseline__raw__xgb' completed.
----------------------------------------
Running fe01__family experiments...
running exp: {'name': 'fe01__family__logreg', 'features': ['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize', 'IsAlone'], 'feature_engineering': [<function add_family_features at 0x0000028FD1B00820>], 'preprocessing': {'numeric_features': ['Age', 'Fare', 'FamilySize', 'IsAlone'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'logreg', 'model_params': {'max_iter': 1000, 'random_state': 42}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Feature engineering 01: replaces SibSp/Parch with FamilySize and IsAlone.', 'stage': 'fe01', 'feature_group': 'family', 'group': 'fe01__family', 'domain': 'family'}
Running experiment: fe01__family__logreg
Applying feature: add_family_features
Features after add_family_features: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'FamilySize', 'IsAlone']

Experiment 'fe01__family__logreg' results:
  stage: fe01
  feature_group: family
  model_name: logreg
  group: fe01__family
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.795
  test_accuracy_std: 0.016
  train_accuracy_mean: 0.806
  train_accuracy_std: 0.005
  test_precision_mean: 0.755
  test_precision_std: 0.038
  train_precision_mean: 0.766
  train_precision_std: 0.007
  test_recall_mean: 0.693
  test_recall_std: 0.038
  train_recall_mean: 0.711
  train_recall_std: 0.012
  test_f1_mean: 0.721
  test_f1_std: 0.021
  train_f1_mean: 0.738
  train_f1_std: 0.008
  fit_time_mean: 0.022
  score_time_mean: 0.014
  domain: family
  notes: Feature engineering 01: replaces SibSp/Parch with FamilySize and IsAlone.

Experiment 'fe01__family__logreg' completed.
----------------------------------------
running exp: {'name': 'fe01__family__knn', 'features': ['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize', 'IsAlone'], 'feature_engineering': [<function add_family_features at 0x0000028FD1B00820>], 'preprocessing': {'numeric_features': ['Age', 'Fare', 'FamilySize', 'IsAlone'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'knn', 'model_params': {'n_neighbors': 5}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Feature engineering 01: replaces SibSp/Parch with FamilySize and IsAlone.', 'stage': 'fe01', 'feature_group': 'family', 'group': 'fe01__family', 'domain': 'family'}
Running experiment: fe01__family__knn
Applying feature: add_family_features
Features after add_family_features: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'FamilySize', 'IsAlone']

Experiment 'fe01__family__knn' results:
  stage: fe01
  feature_group: family
  model_name: knn
  group: fe01__family
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.805
  test_accuracy_std: 0.027
  train_accuracy_mean: 0.862
  train_accuracy_std: 0.008
  test_precision_mean: 0.767
  test_precision_std: 0.052
  train_precision_mean: 0.842
  train_precision_std: 0.014
  test_recall_mean: 0.711
  test_recall_std: 0.037
  train_recall_mean: 0.789
  train_recall_std: 0.011
  test_f1_mean: 0.737
  test_f1_std: 0.032
  train_f1_mean: 0.815
  train_f1_std: 0.01
  fit_time_mean: 0.016
  score_time_mean: 0.023
  domain: family
  notes: Feature engineering 01: replaces SibSp/Parch with FamilySize and IsAlone.

Experiment 'fe01__family__knn' completed.
----------------------------------------
running exp: {'name': 'fe01__family__svc', 'features': ['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize', 'IsAlone'], 'feature_engineering': [<function add_family_features at 0x0000028FD1B00820>], 'preprocessing': {'numeric_features': ['Age', 'Fare', 'FamilySize', 'IsAlone'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'svc', 'model_params': {'C': 1.0, 'kernel': 'rbf', 'gamma': 'scale', 'probability': False, 'random_state': 42}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Feature engineering 01: replaces SibSp/Parch with FamilySize and IsAlone.', 'stage': 'fe01', 'feature_group': 'family', 'group': 'fe01__family', 'domain': 'family'}
Running experiment: fe01__family__svc
Applying feature: add_family_features
Features after add_family_features: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'FamilySize', 'IsAlone']

Experiment 'fe01__family__svc' results:
  stage: fe01
  feature_group: family
  model_name: svc
  group: fe01__family
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.826
  test_accuracy_std: 0.026
  train_accuracy_mean: 0.834
  train_accuracy_std: 0.008
  test_precision_mean: 0.815
  test_precision_std: 0.036
  train_precision_mean: 0.827
  train_precision_std: 0.012
  test_recall_mean: 0.707
  test_recall_std: 0.058
  train_recall_mean: 0.716
  train_recall_std: 0.018
  test_f1_mean: 0.756
  test_f1_std: 0.042
  train_f1_mean: 0.768
  train_f1_std: 0.012
  fit_time_mean: 0.021
  score_time_mean: 0.022
  domain: family
  notes: Feature engineering 01: replaces SibSp/Parch with FamilySize and IsAlone.

Experiment 'fe01__family__svc' completed.
----------------------------------------
running exp: {'name': 'fe01__family__decision_tree', 'features': ['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize', 'IsAlone'], 'feature_engineering': [<function add_family_features at 0x0000028FD1B00820>], 'preprocessing': {'numeric_features': ['Age', 'Fare', 'FamilySize', 'IsAlone'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'decision_tree', 'model_params': {'max_depth': 4, 'min_samples_leaf': 5, 'random_state': 42}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Feature engineering 01: replaces SibSp/Parch with FamilySize and IsAlone.', 'stage': 'fe01', 'feature_group': 'family', 'group': 'fe01__family', 'domain': 'family'}
Running experiment: fe01__family__decision_tree
Applying feature: add_family_features
Features after add_family_features: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'FamilySize', 'IsAlone']

Experiment 'fe01__family__decision_tree' results:
  stage: fe01
  feature_group: family
  model_name: decision_tree
  group: fe01__family
  status: success
  error_type:
  error_message:
  test_accuracy_mean: 0.806
  test_accuracy_std: 0.021
  train_accuracy_mean: 0.832
  train_accuracy_std: 0.004
  test_precision_mean: 0.82
  test_precision_std: 0.032
  train_precision_mean: 0.859
  train_precision_std: 0.046
  test_recall_mean: 0.64
  test_recall_std: 0.1
  train_recall_mean: 0.681
  train_recall_std: 0.043
  test_f1_mean: 0.712
  test_f1_std: 0.056
  train_f1_mean: 0.757
  train_f1_std: 0.011
  fit_time_mean: 0.016
  score_time_mean: 0.017

In [23]:
# print("Experiment Configurations:")
# print(exp_configs)
# for exp_config in exp_configs:
#     print(exp_config)

In [24]:
# Work flow for running an experiment group, comparing it to the baseline, and generating a report. 
# This is the main workflow for analyzing the results of an experiment group and generating insights from it.
workflow = run_experiment_group_workflow(
    df=train_df,
    experiment_configs=exp_configs,
    target=TARGET,
    save=True,
)
# print("Workflow completed. Here are the results:")
# print("Comparison between baseline and feature engineering group:")
# print(workflow["comparison"])
# print("Summary of comparison:")
# print(workflow["summary"])
# print("Leaderboard:")
# print(workflow["leaderboard"])

running exp: {'name': 'cb03__age_imputed_title_Pclass_and_bins__logreg', 'features': ['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked', 'Age', 'Age_bin'], 'feature_engineering': [<function age_imputed_by_title_pclass at 0x0000028FD1B009D0>, <function add_age_bin at 0x0000028FD1B00CA0>], 'preprocessing': {'numeric_features': ['SibSp', 'Parch', 'Age'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass', 'Age_bin'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'logreg', 'model_params': {'max_iter': 1000, 'random_state': 42}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Combo 03: Exploring the effect of using both raw age and age bins.', 'stage': 'cb03', 'feature_group': 'age_imputed_title_Pclass_and_bins', 'group': 'cb03__age_imputed_title_Pclass_and_bins', 'domain': 'age'}
running exp: {'name': 'cb03__age_imputed_title_Pclass_and_bins__knn', 'features': ['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked', 'Age', 'Age_bin'], 'feature_engineering': [<function age_imputed_by_title_pclass at 0x0000028FD1B009D0>, <function add_age_bin at 0x0000028FD1B00CA0>], 'preprocessing': {'numeric_features': ['SibSp', 'Parch', 'Age'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass', 'Age_bin'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'knn', 'model_params': {'n_neighbors': 5}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Combo 03: Exploring the effect of using both raw age and age bins.', 'stage': 'cb03', 'feature_group': 'age_imputed_title_Pclass_and_bins', 'group': 'cb03__age_imputed_title_Pclass_and_bins', 'domain': 'age'}
running exp: {'name': 'cb03__age_imputed_title_Pclass_and_bins__svc', 'features': ['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked', 'Age', 'Age_bin'], 'feature_engineering': [<function age_imputed_by_title_pclass at 0x0000028FD1B009D0>, <function add_age_bin at 0x0000028FD1B00CA0>], 'preprocessing': {'numeric_features': ['SibSp', 'Parch', 'Age'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass', 'Age_bin'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'svc', 'model_params': {'C': 1.0, 'kernel': 'rbf', 'gamma': 'scale', 'probability': False, 'random_state': 42}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Combo 03: Exploring the effect of using both raw age and age bins.', 'stage': 'cb03', 'feature_group': 'age_imputed_title_Pclass_and_bins', 'group': 'cb03__age_imputed_title_Pclass_and_bins', 'domain': 'age'}
running exp: {'name': 'cb03__age_imputed_title_Pclass_and_bins__decision_tree', 'features': ['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked', 'Age', 'Age_bin'], 'feature_engineering': [<function age_imputed_by_title_pclass at 0x0000028FD1B009D0>, <function add_age_bin at 0x0000028FD1B00CA0>], 'preprocessing': {'numeric_features': ['SibSp', 'Parch', 'Age'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass', 'Age_bin'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'decision_tree', 'model_params': {'max_depth': 4, 'min_samples_leaf': 5, 'random_state': 42}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Combo 03: Exploring the effect of using both raw age and age bins.', 'stage': 'cb03', 'feature_group': 'age_imputed_title_Pclass_and_bins', 'group': 'cb03__age_imputed_title_Pclass_and_bins', 'domain': 'age'}
running exp: {'name': 'cb03__age_imputed_title_Pclass_and_bins__random_forest', 'features': ['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked', 'Age', 'Age_bin'], 'feature_engineering': [<function age_imputed_by_title_pclass at 0x0000028FD1B009D0>, <function add_age_bin at 0x0000028FD1B00CA0>], 'preprocessing': {'numeric_features': ['SibSp', 'Parch', 'Age'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass', 'Age_bin'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'random_forest', 'model_params': {'n_estimators': 200, 'max_depth': 5, 'min_samples_leaf': 3, 'random_state': 42, 'n_jobs': -1}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Combo 03: Exploring the effect of using both raw age and age bins.', 'stage': 'cb03', 'feature_group': 'age_imputed_title_Pclass_and_bins', 'group': 'cb03__age_imputed_title_Pclass_and_bins', 'domain': 'age'}
running exp: {'name': 'cb03__age_imputed_title_Pclass_and_bins__extra_trees', 'features': ['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked', 'Age', 'Age_bin'], 'feature_engineering': [<function age_imputed_by_title_pclass at 0x0000028FD1B009D0>, <function add_age_bin at 0x0000028FD1B00CA0>], 'preprocessing': {'numeric_features': ['SibSp', 'Parch', 'Age'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass', 'Age_bin'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'extra_trees', 'model_params': {'n_estimators': 200, 'max_depth': 5, 'min_samples_leaf': 3, 'random_state': 42, 'n_jobs': -1}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Combo 03: Exploring the effect of using both raw age and age bins.', 'stage': 'cb03', 'feature_group': 'age_imputed_title_Pclass_and_bins', 'group': 'cb03__age_imputed_title_Pclass_and_bins', 'domain': 'age'}
running exp: {'name': 'cb03__age_imputed_title_Pclass_and_bins__xgb', 'features': ['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked', 'Age', 'Age_bin'], 'feature_engineering': [<function age_imputed_by_title_pclass at 0x0000028FD1B009D0>, <function add_age_bin at 0x0000028FD1B00CA0>], 'preprocessing': {'numeric_features': ['SibSp', 'Parch', 'Age'], 'onehot_features': ['Sex', 'Embarked'], 'ordinal_features': ['Pclass', 'Age_bin'], 'numeric_imputer': 'median', 'categorical_imputer': 'most_frequent', 'scaler': 'standard'}, 'model_name': 'xgb', 'model_params': {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.05, 'subsample': 0.8, 'colsample_bytree': 0.8, 'random_state': 42, 'eval_metric': 'logloss'}, 'evaluation': {'method': 'cross_validation', 'cv': 5, 'scoring': ['accuracy', 'precision', 'recall', 'f1'], 'return_train_score': True, 'n_jobs': -1}, 'notes': 'Combo 03: Exploring the effect of using both raw age and age bins.', 'stage': 'cb03', 'feature_group': 'age_imputed_title_Pclass_and_bins', 'group': 'cb03__age_imputed_title_Pclass_and_bins', 'domain': 'age'}

In [25]:
# Generate a full report for the workflow, including the comparison, summary, and leaderboard. 
# This will be a markdown report that can be easily shared and visualized.
# Mainly used for generating the report for the notebook, but can also be used for generating reports for individual experiment groups or comparisons.
full_report = workflow_report(workflow)
print("Full workflow report:")
print()
print('Report')
print(full_report['report'])
print()
print('Leaderboard')
print(full_report['leaderboard'])
print()

# For combos:
all_results = load_results()
references = ['cb01__age_and_bins','cb02__age_imputed_title_and_bins']
for reference in references:
    comparison = compare_experiment_groups(
                results_df=all_results,
                reference_group=reference,
                compare_groups=[exp_configs],
            )
    print(f"Comparison summary:")
    print(comparison[["reference_group", "compare_group", "model_name", "test_accuracy_mean_delta", "test_f1_mean_delta"]].to_markdown())
    print()

Full workflow report:

Report
### cb03__age_imputed_title_Pclass_and_bins

_Description pending._

<details>
<summary>Conclusion</summary>


#### Interpretation

- Verdict: model_specific_positive
- Recommended for specific models:
  - logreg: test_accuracy_mean: 0.016
    - Secondary gains:
      - test_f1_mean: 0.017
  - svc: test_accuracy_mean: 0.004
  - random_forest: test_accuracy_mean: 0.006
  - extra_trees: test_accuracy_mean: 0.013
    - Secondary gains:
      - test_f1_mean: 0.02
- Notable secondary improvements in non-recommended models:
  - decision_tree: test_f1_mean: 0.012


#### Conclusion

_Conclusion pending._

</details>

<details>
<summary>Experiment details</summary>

#### Comparison vs baseline__raw

| reference_group   | compare_group                           | model_name    |   test_accuracy_mean_reference |   test_accuracy_mean_compare |   test_accuracy_mean_delta |   test_f1_mean_reference |   test_f1_mean_compare |   test_f1_mean_delta |
|:------------------|:----------------------------------------|:--------------|-------------------------------:|-----------------------------:|---------------------------:|-------------------------:|-----------------------:|---------------------:|
| baseline__raw     | cb03__age_imputed_title_Pclass_and_bins | logreg        |                          0.786 |                        0.802 |                      0.016 |                    0.713 |                  0.73  |                0.017 |
| baseline__raw     | cb03__age_imputed_title_Pclass_and_bins | knn           |                          0.809 |                        0.808 |                     -0.001 |                    0.742 |                  0.73  |               -0.012 |
| baseline__raw     | cb03__age_imputed_title_Pclass_and_bins | svc           |                          0.827 |                        0.831 |                      0.004 |                    0.76  |                  0.766 |                0.006 |
| baseline__raw     | cb03__age_imputed_title_Pclass_and_bins | decision_tree |                          0.803 |                        0.804 |                      0.001 |                    0.702 |                  0.714 |                0.012 |
| baseline__raw     | cb03__age_imputed_title_Pclass_and_bins | random_forest |                          0.822 |                        0.828 |                      0.006 |                    0.744 |                  0.751 |                0.007 |
| baseline__raw     | cb03__age_imputed_title_Pclass_and_bins | extra_trees   |                          0.804 |                        0.817 |                      0.013 |                    0.721 |                  0.741 |                0.02  |
| baseline__raw     | cb03__age_imputed_title_Pclass_and_bins | xgb           |                          0.826 |                        0.827 |                      0.001 |                    0.758 |                  0.756 |               -0.002 |

#### Summary

| compare_group                           |   test_accuracy_mean_delta_mean |   test_accuracy_mean_delta_min |   test_accuracy_mean_delta_max |   test_f1_mean_delta_mean |   test_f1_mean_delta_min |   test_f1_mean_delta_max |
|:----------------------------------------|--------------------------------:|-------------------------------:|-------------------------------:|--------------------------:|-------------------------:|-------------------------:|
| cb03__age_imputed_title_Pclass_and_bins |                      0.00571429 |                         -0.001 |                          0.016 |                0.00685714 |                   -0.012 |                     0.02 |

</details>

Leaderboard
| experiment                                   | model_name    |   test_accuracy_mean |   test_f1_mean |
|:---------------------------------------------|:--------------|---------------------:|---------------:|
| fe05__title__xgb                             | xgb           |                0.836 |          0.772 |
| fe05__title__svc                             | svc           |                0.834 |          0.771 |
| fe11__age_bin__random_forest                 | random_forest |                0.833 |          0.759 |
| fe05__title__random_forest                   | random_forest |                0.832 |          0.768 |
| cb02__age_imputed_title_and_bins__xgb        | xgb           |                0.832 |          0.762 |
| cb02__age_imputed_title_and_bins__svc        | svc           |                0.832 |          0.767 |
| fe09__ticket_group_size__svc                 | svc           |                0.832 |          0.77  |
| fe04__cabin_features__xgb                    | xgb           |                0.832 |          0.767 |
| cb03__age_imputed_title_Pclass_and_bins__svc | svc           |                0.831 |          0.766 |
| fe06__age_imputation_title__svc              | svc           |                0.829 |          0.764 |

Comparison summary:
|    | reference_group    | compare_group                           | model_name    |   test_accuracy_mean_delta |   test_f1_mean_delta |
|---:|:-------------------|:----------------------------------------|:--------------|---------------------------:|---------------------:|
|  0 | cb01__age_and_bins | cb03__age_imputed_title_Pclass_and_bins | logreg        |                      0.007 |                0.008 |
|  1 | cb01__age_and_bins | cb03__age_imputed_title_Pclass_and_bins | knn           |                      0.013 |                0.012 |
|  2 | cb01__age_and_bins | cb03__age_imputed_title_Pclass_and_bins | svc           |                      0.003 |                0.004 |
|  3 | cb01__age_and_bins | cb03__age_imputed_title_Pclass_and_bins | decision_tree |                     -0.003 |               -0.005 |
|  4 | cb01__age_and_bins | cb03__age_imputed_title_Pclass_and_bins | random_forest |                      0     |               -0.004 |
|  5 | cb01__age_and_bins | cb03__age_imputed_title_Pclass_and_bins | extra_trees   |                      0.002 |                0.003 |
|  6 | cb01__age_and_bins | cb03__age_imputed_title_Pclass_and_bins | xgb           |                      0     |                0.002 |

Comparison summary:
|    | reference_group                  | compare_group                           | model_name    |   test_accuracy_mean_delta |   test_f1_mean_delta |
|---:|:---------------------------------|:----------------------------------------|:--------------|---------------------------:|---------------------:|
|  0 | cb02__age_imputed_title_and_bins | cb03__age_imputed_title_Pclass_and_bins | logreg        |                      0.007 |                0.01  |
|  1 | cb02__age_imputed_title_and_bins | cb03__age_imputed_title_Pclass_and_bins | knn           |                      0.004 |                0.005 |
|  2 | cb02__age_imputed_title_and_bins | cb03__age_imputed_title_Pclass_and_bins | svc           |                     -0.001 |               -0.001 |
|  3 | cb02__age_imputed_title_and_bins | cb03__age_imputed_title_Pclass_and_bins | decision_tree |                     -0.003 |               -0.002 |
|  4 | cb02__age_imputed_title_and_bins | cb03__age_imputed_title_Pclass_and_bins | random_forest |                      0.001 |                0     |
|  5 | cb02__age_imputed_title_and_bins | cb03__age_imputed_title_Pclass_and_bins | extra_trees   |                     -0.001 |                0     |
|  6 | cb02__age_imputed_title_and_bins | cb03__age_imputed_title_Pclass_and_bins | xgb           |                     -0.005 |               -0.006 |

In [26]:
# import pprint
# Feature_effect = analyze_feature_effect(workflow['comparison'])
# pprint.pprint(Feature_effect)

In [27]:
# Reminder of how to run a single experiment if needed. 
# This is useful for when we want to generate reports or comparisons without rerunning all experiments.

# exp_config = [exp_config]
# exp_result = run_experiments(train_df, exp_config, target=TARGET,)
# exp_report = experiment_report(exp_result, exp_config, print_report=True)
# save_results(exp_result)
# save_configs(exp_config)

In [28]:
# Summary for baseline experiment to use in report, 
# since we can't compare it to itself.

# baseline_summary = baseline_summary_to_markdown(exp_result)
# print("Baseline summary:")
# print(baseline_summary)

In [29]:
# Reminder for how to load results and configs if needed. 
# This is useful for when we want to generate reports or comparisons without rerunning all experiments.

# all_results = load_results()
# print("Loaded results:")
# print(all_results)

# all_configs = load_configs()
# print("Loaded configs:")
# print(all_configs)

In [30]:
# print(workflow["all_results"])

In [31]:
# for model in MODEL_REGISTRY:
#     model_progression_df = model_progression(workflow["all_results"], model_name=model, metric="test_accuracy_mean")
#     print(f"Model progression for {model}:")
#     print(model_progression_df)
#     print()

In [32]:
# bins = [0, 14, 35, 60, 100]
# labels = ['0', '2', '3', '1']
# exp_df['Age_bin'] = pd.cut(exp_df['Age'], bins=bins, labels=labels, right=False)

In [33]:
# for age in range(0,18):
#     test_df = exp_df[exp_df['Age'] == age][['Age','Survived']]
#     test_df = test_df.groupby('Survived').value_counts()
#     print(test_df)

In [34]:
def domain_best_by_model(
    results_df,
    domain,
    metric="test_accuracy_mean",
    include_baseline=True,
    only_success=True,
):
    df = results_df.copy()

    if only_success and "status" in df.columns:
        df = df[df["status"] == "success"]

    if metric not in df.columns:
        raise ValueError(f"Metric '{metric}' not found in results dataframe.")

    domain_df = df[df["domain"] == domain]

    if include_baseline:
        baseline_df = df[df["group"] == "baseline__raw"]
        domain_df = pd.concat([baseline_df, domain_df], ignore_index=True)

    if domain_df.empty:
        raise ValueError(f"No results found for domain: {domain}")

    best_rows = (
        domain_df
        .sort_values(metric, ascending=False)
        .groupby("model_name", as_index=False)
        .first()
    )

    columns = [
        "model_name",
        "experiment",
        "group",
        "domain",
        metric,
        "test_f1_mean",
    ]

    columns = [col for col in columns if col in best_rows.columns]

    return (
        best_rows[columns]
        .sort_values(metric, ascending=False)
        .reset_index(drop=True)
    )

In [ ]:
# print(all_results.columns)
# print(all_results.to_markdown())

age_best = domain_best_by_model(
    results_df=all_results,
    domain="age",
    metric="test_accuracy_mean",
)

age_best

# print(pd.DataFrame(load_configs()))

,model_name,experiment,group,domain,test_accuracy_mean,test_f1_mean
0,random_forest,fe11__age_bin__random_forest,fe11__age_bin,age,0.833,0.759
1,svc,cb02__age_imputed_title_and_bins__svc,cb02__age_imputed_title_and_bins,age,0.832,0.767
2,xgb,cb02__age_imputed_title_and_bins__xgb,cb02__age_imputed_title_and_bins,age,0.832,0.762
3,extra_trees,fe11__age_bin__extra_trees,fe11__age_bin,age,0.819,0.737
4,knn,fe11__age_bin__knn,fe11__age_bin,age,0.810,0.737
5,decision_tree,fe11__age_bin__decision_tree,fe11__age_bin,age,0.809,0.722
6,logreg,cb03__age_imputed_title_Pclass_and_bins__logreg,cb03__age_imputed_title_Pclass_and_bins,age,0.802,0.730

In [37]:
def domain_best_by_model_with_baseline_delta(
    results_df,
    domain,
    metric="test_accuracy_mean",
):
    best_df = domain_best_by_model(
        results_df=results_df,
        domain=domain,
        metric=metric,
        include_baseline=True,
    )

    baseline = (
        results_df[results_df["group"] == "baseline__raw"]
        [["model_name", metric]]
        .rename(columns={metric: f"{metric}_baseline"})
    )

    best_df = best_df.merge(baseline, on="model_name", how="left")
    best_df[f"{metric}_delta_vs_baseline"] = (
        best_df[metric] - best_df[f"{metric}_baseline"]
    )

    return best_df

In [38]:
age_best_delta = domain_best_by_model_with_baseline_delta(
    results_df=all_results,
    domain="age",
    metric="test_accuracy_mean",
)

age_best_delta

,model_name,experiment,group,domain,test_accuracy_mean,test_f1_mean,test_accuracy_mean_baseline,test_accuracy_mean_delta_vs_baseline
0,random_forest,fe11__age_bin__random_forest,fe11__age_bin,age,0.833,0.759,0.822,0.011
1,svc,cb02__age_imputed_title_and_bins__svc,cb02__age_imputed_title_and_bins,age,0.832,0.767,0.827,0.005
2,xgb,cb02__age_imputed_title_and_bins__xgb,cb02__age_imputed_title_and_bins,age,0.832,0.762,0.826,0.006
3,extra_trees,fe11__age_bin__extra_trees,fe11__age_bin,age,0.819,0.737,0.804,0.015
4,knn,fe11__age_bin__knn,fe11__age_bin,age,0.810,0.737,0.809,0.001
5,decision_tree,fe11__age_bin__decision_tree,fe11__age_bin,age,0.809,0.722,0.803,0.006
6,logreg,cb03__age_imputed_title_Pclass_and_bins__logreg,cb03__age_imputed_title_Pclass_and_bins,age,0.802,0.730,0.786,0.016